### ISSUE TITLE
Example for morphImages

### ISSUE THREAD

**Issue by MagicalTux** [Danack/Imagick-demos#10]
An example is missing for http://php.net/manual/en/imagick.morphimages.php

(actually I've been trying to use it but the documentation available on php.net makes it difficult to get a result)

**Comment by MagicalTux** [comment]
Actually managed to get a result.

* You need to make sure you're on the first of the two images you want to morph (for example if using readImages, you need to setIteratorIndex(0)).
* Function will return a new imagick object with number of generated frames + 2 (the original two)

**Comment by Danack** [comment]
Yep, it needs the internal iterator resetting similar to https://github.com/mkoppanen/imagick/issues/94

@MagicalTux  What do you think about having the Imagick::morphImages method changed to be 

    Imagick::morphImages($frames, $resetIterator = true)

i.e. by default have Imagick reset the iterator when someone calls morphImages, unless they specifically request that not to happen?

**Comment by MagicalTux** [comment]
Adding an optional $resetIterator parameter to these functions seems indeed to be a good idea. I am usually not for changing a function's default behavior, however in this case I would guess cases where someone only want to morph (or append) only some images of a set without creating a subset are very rare.

(Also it seems that http://php.net/imagick is missing method Imagick::resetIterator().)

**Comment by Danack** [comment]
The example is done: http://phpimagick.com/Imagick/morphImages
