### ISSUE TITLE
Difference?

### ISSUE THREAD

**Issue by socialblogsite** [Danack/Imagick-demos#11]
I have found an extensive tutorial for finding similar images at http://www.imagemagick.org/Usage/compare/ with a command line version of imagick but in another website the difference filter is just noted as "doesn't work". 

Is that so? Do you have any resource/link for me to find info about that?
I hope I can merge this script https://www.wphub.com/44-ways-hack-wordpress-media-library/ with the one above to find similar images in wordpress (one of my scripts uploaded the same image over and over. It shows how novice I am in PHP :(   Any help in the right direction would be appreciated :)

**Comment by Danack** [comment]
>  in another website the difference filter is just noted as "doesn't work".

I am not sure how I meant to respond to 'another website'.

Sorry, I don't have any advice to give right now on comparing images. It's a big issue, and not answerable with the time I have available right now.
