### ISSUE TITLE
Performance recommendations?

### ISSUE THREAD

**Issue by vtjiles** [Danack/Imagick-demos#12]
My CPU is going over 100% when a page loads and needs multiple images processed at once (10-20). I can even see it with a single image spiking to 50%. I read about MAGICK_THREAD_LIMIT and OMP_THREAD_LIMIT, but setting them didn't seem to help or may have done it wrong with the putenv function. Do you have any examples or insight into what I could do to reduce the overall CPU usage?  

I know adding more horsepower or pre-processing would help, but am trying to keep it all real-time and am ok if it takes longer to load up the images.

Appreciate any thoughts.

**Comment by Danack** [comment]
I don't recommend running Imagick in a webserver at all. It's only sane to have it running as a background task. As the Imagick [extension says](https://github.com/mkoppanen/imagick#security):

> Do not run Imagick in a server that is directly accessible from outside your network. It is better to either use it as a background task using something like [SupervisorD](http://supervisord.org/) or to run it in a separate server that is not directly access on the internet.

The most efficient performance is single threaded, and if you have lots of images to process at once, scaling out by using multiple background workers, each processing a single image is the way to have images be generated the fastest.

This code isn't very clear but the phpimagick.com site uses asynchronous loading of images, to make the site feel fast when it isn't always. 

The async loader is [here](https://github.com/Danack/Imagick-demos/blob/master/imagick/js/AsyncImage.js) and the server just returns a 420 HTTP error code while the images are still being generated.

**Comment by vtjiles** [comment]
That's what I figured. At least with a separate image processing box that can scale independently. Thanks for your input.
