### ISSUE TITLE
Imagemagick vs. Imagick

### ISSUE THREAD

**Issue by gree303** [Danack/Imagick-demos#18]
Can you tell where the difference between IM and Imagick is?
I'd like to develop a small script on Imagick. But I'm not sure if it supports all the features of ImageMagick (16 bit for example).

Further it does not support plugins; is there any way around this limitation?
Many Thanks

**Comment by Danack** [comment]
ImageMagick is the library that does the image processing.

Imagick is a PHP extension that allows you to call the ImageMagick library from PHP.

The exact features available in Imagick depend on how the ImageMagick library was compiled. If it was compiled as 16bit image processing, then that is what will be available in PHP.

> Further it does not support plugins

I don't know what you mean by a plugin, so cannot offer advice about a workaround.

**Comment by gree303** [comment]
Thanks for all details.
