### ISSUE TITLE
this is not showing any output

### ISSUE THREAD

**Issue by shrutiakki** [Danack/Imagick-demos#21]
Reported from ImagickDraw::rectangle this code is not working for  me i mean whether i need modify /add anything  in that code don't know so please help me to get output for that and also
how to draw nested rectangle and writing text into that inner rectangle.

**Comment by Danack** [comment]
> is not working for me

That code (obviously) works for me. How is it not working for you - aka what is it doing instead of working.

> how to draw nested rectangle and writing text into that inner rectangle.

What have you tried so far?

**Comment by Danack** [comment]
Closing, no feedback.
