### ISSUE TITLE
Imagick is not working in WIMP environment for PHP-website based on Piwigo

### ISSUE THREAD

**Issue by sthopd** [Danack/Imagick-demos#23]
Imagick DLL is not working in WIMP environment for PHP-website based on Piwigo
Hello,

On my webserver I have a WIMP environment running: Windows10 pro 32bit, IIS 10, MySQL and PHP websites.
I have the PHP-based website of the Piwigo platform running (= photo gallery website software which I use for digital art exposition). 
To display animated GIF files, I have replaced the standard Graphics Library by ImageMagick 6.9.3-7 .
This does not work in the context of DLLs available for PHP, meaning: no generation of resized instances, such as thumbnails etc.
Even normal/still GIFs and JPGs are not processed anymore when uploaded.
Via a Command Prompt I can instruct Imagick (running as Windows software), by means of a script, to make a resized instance of the original.
I would have to do this manually for each image (50 times) and for each size specification (4x50 ?).
I do not know the script parameters for sizes other than thumbnails. Do you have script-examples of different sizes?
Do you know what to do to get the installation of Imagick running properly as the default Graphics Library within Piwigo?
Please ask me which technical information you need to solve this problem, and I will gather all relevant data for you.

Thanking you in advance, I remain.
Friendly regards,
Rolf Snijders
rolf.snijders@ziggo.nl

------------
Piwigo version: 2.8.6
PHP version: 5.6.0 
MySQL version: 5.5.54
WIMP platform: Windows 10 pro 32bit, IIS 10 webserver, MySql, PHP.
Piwigo URL: http://www.rolfsnijders.net/?br=gim

-----
Example of working manual script for command prompt:
"C:/aSubdirectory/ImageMagick-7.0.5-Q16/convert" "C:/aSubdirectory/piwigo/galleries/OriginalCategories/BeautyMotives/Animations/FapTrailer8-animationToFro2-RGES.gif" -coalesce -filter Lanczos -resize 144x144! -quality 97 -sampling-factor 4:2:2 -layers OptimizePlus "C:/aSubdirectory/piwigo/_data/i/galleries/OriginalCategories/BeautyMotives/Animations/FapTrailer8-animationToFro2-RGES-th.gif"
-----

**Comment by Danack** [comment]
> Via a Command Prompt I can instruct Imagick (running as Windows software), by means of a script, to make a resized instance of the original.

If it works in the command line, then it's a problem with the IIS configuration, or permissions loading the DLL.

Other than that, I'm sorry but I just don't have the time or interest in debugging why someone's software isn't installed properly.

**Comment by sthopd** [comment]
Hello Danack,
Do you have a tutorial for implementing Imagick DLL's etc. for PHP in a WIMP environment?
Thanks, Rolf

**Comment by Danack** [comment]
I actually don't really - I have never used IIS. About the only advice I can give is to download both ImageMagick and Imagick from the same place, and from windows.php.net should work.

Download ImageMagick from:
http://windows.php.net/downloads/pecl/deps/

Download Imagick from:
http://windows.php.net/downloads/pecl/releases/imagick/

**Comment by sthopd** [comment]
Hello Danack,

At last I got Imagick as 'add-on' for Piwigo working.
I have installed other/newer versions of relevant software in my WIMP environment:

1. vc_redist.x86.exe [= Visual c++ v.14 (for VisualStudio 15) ].
2. The 9 DLL's from php_imagick-3.4.3rc4-7.1-nts-vc14-x86.zip.

Friendly regards,
Rolf
