### ISSUE TITLE
Problems with FastCgi in PHP v.7.1.7 when Imagick is active

### ISSUE THREAD

**Issue by sthopd** [Danack/Imagick-demos#25]
Hello expert,
Recently, my websites running (on the same 32-bit webserver) under PHP version 7.1.7 crash many times (Internal Server Error 500) or are 'frozen' in a process (Loading data...) which does not end.
The Internal Server Error is traced back to a FastCGI problems/failures.
Sometimes, refreshing the browser-window (F5 or ctrl-R) helps, but often I have to restart my webserver entirely (hard-reboot).

Error message:
"HTTP Error 500.0 - Internal Server Error. The FastCGI process has failed frequently recently. Try the request again in a while."

A. Example Piwigo (online photo album showcase):
Clicking in album categories of Piwigo and on individual photo's for detail-page cause the same FastCGI error message.
This happens especially when handling GIF-animations, which are resized on the fly by the Imagick-plugin.
(The website also contains the PicLens 3D Wall plugin [Adobe Flash]).

The Imagick-plugin in Piwigo needs C++ runtime:
This will not work in combination with the latest version: Microsoft Visual Studio C++ 2017 Redistributable (x86) 14.10.25017 .
This may work with: Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.23026 , but often results in 'frozen' webserver.

B. Example Piwik (web-statistics analysis): 
Clicking on the webpages of Piwik, navigation towards a monitored website:
Piwik: Settings | Websites | Manage -->
Piwik-site page gets stuck in 'Loading data...' or displays error message:
"HTTP Error 500.0 - Internal Server Error. The FastCGI process has failed frequently recently. Try the request again in a while."
The statistically calculated content of the Piwigo-site (visitor activities) is often blanc in Piwik detail-pages, and sometimes filled with appropriate data.

---
Overal performance: these PHP-sites have become slow and unpredictable.
(As webbrowser, I used the updated versions of: Edge, Firefox and Opera.)

Do you know what the correct combination/implementation/settings should be, to get these websites working properly, regarding versions of: Piwik, Piwigo, Imagick, Visual C++ Redistributable, PHP - FastCgi ?

Environment:
Piwigo 2.9.2 (www.rolfsnijders.net)
Piwik 3.2.0 

Operating system: WINNT: Windows 10 prof 32bit, webserver: IIS 10 
PHP: 7.1.7 [2017-11-21]
MySQL: 5.5.54 

Imagick Graphics Library: External ImageMagick 7.0.5-1
Installed on webserver: 
a) ImageMagick-7.0.5-1-Q16-x86-dll.exe (desktop software).
b) Relevant content of: php_imagick-3.4.3rc4-7.1-nts-vc14-x86.zip (PHP-extension).

Friendly regards,
Rolf

**Comment by Danack** [comment]
Sorry - I don't have time to really debug anything windows related, but you need to get real error messages from your server, not just '500'
https://stackoverflow.com/questions/845021/how-to-get-useful-error-messages-in-php

And the only versions I can recommend downloading are those from:
http://windows.php.net/downloads/pecl/releases/imagick/
http://windows.php.net/downloads/pecl/deps/

for both Imagick and ImageMagick.
