### ISSUE TITLE
$imagick->setbackgroundcolor('rgb(64, 64, 64)');

### ISSUE THREAD

**Issue by Doccos** [Danack/Imagick-demos#26]
Reported from Imagick::thumbnailImage

$imagick->setbackgroundcolor('rgb(64, 64, 64)'); should be $imagick->setImagebackgroundcolor('rgb(64, 64, 64)');

**Comment by Danack** [comment]
Hi,

Can you say what difference you think this makes?

Or provide an example image where that code change results in a difference?

cheers
Dan

**Comment by Doccos** [comment]
$imagick->setbackgroundcolor('rgb(64, 64, 64)'); has no effect when i thumbnail an image.
$imagick->setImagebackgroundcolor('rgb(64, 64, 64)'); sets the backgroundcolor

**Comment by Danack** [comment]
Could you also provide a test image please?

**Comment by Danack** [comment]
Closing due to no response.
