### ISSUE TITLE
Need code to extend the image vertically

### ISSUE THREAD

**Issue by Kembreg** [Danack/Imagick-demos#27]
Reported from Tutorial::edgeExtend

This page: http://phpimagick.com/Tutorial/edgeExtend provides an example for extending an image horizontally. Would appreciate an example to extend an image vertically.

Also, the example is difficult to follow, with comments poorly placed.
Better would be the following code:

$originalWidth = $img->getImageWidth();
$desiredWidth = $originalWidth+120;
$XFactor=$originalWidth / $desiredWidth; 
$XOffset=($desiredWidth - $originalWidth) / 2;
$img->setImageVirtualPixelMethod(Imagick::VIRTUALPIXELMETHOD_MIRROR);
$img->sampleimage($desiredWidth, $img->getImageHeight()); //Make the image be the desired width.
$points=array($XFactor,0,0,1,$XOffset,0);
$img->distortImage(Imagick::DISTORTION_AFFINEPROJECTION,$points,false);

[In the $points array.... what do the arguments actually do?]

**Comment by Sublan** [comment]
$img->setImageVirtualPixelMethod(Imagick::VIRTUALPIXELMETHOD_EDGE)

**Comment by Danack** [comment]
Closing, don't have bandwidth to support individual requests.
