### ISSUE TITLE
Tier using DI to implement app architecture

### ISSUE THREAD

**Issue by emaygo** [Danack/Imagick-demos#32]
Hello @Danack ,

the phpimagick.com is not working now.  ( `Tier using DI to implement app architecture ) 

We can not look example in the web site.
Please can you check phpimagick.com ?

Thank you

``

**Comment by Danack** [comment]
Oh lawd I am bad with computers.

**Comment by emaygo** [comment]
@Danack  

Your so good.  it's working now.

Thank you very much.

**Comment by Danack** [comment]
The site is now running in a container in a slightly beefier server.

I've put a site monitor on it so should get alerted if it falls over again.
