### ISSUE TITLE
Exception: Undefined class constant 'MORPHOLOGY_EDGE'

### ISSUE THREAD

**Issue by pixobit** [Danack/Imagick-demos#35]
I might be missing something here, but for me a lot of the constants are missing from the Imagick library

**Comment by pixobit** [comment]
Additional information from phpinfo()
imagick module version | 3.4.4
imagick classes | Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator
Imagick compiled with ImageMagick version | ImageMagick 6.7.8-9 2019-02-01 Q16 http://www.imagemagick.org
Imagick using ImageMagick library version | ImageMagick 6.7.8-9 2019-08-08 Q16 http://www.imagemagick.org
ImageMagick copyright | Copyright (C) 1999-2012 ImageMagick Studio LLC
ImageMagick release date | 2019-08-08
ImageMagick number of supported formats: | 209

**Comment by Danack** [comment]
6.7.8-9 was released on 2012-08-10.

You'll need a later version than that for the morphology stuff.
