### ISSUE TITLE
Imagick hang APache server in XAMPP when converting PDF to PNG

### ISSUE THREAD

**Issue by Diamond7** [Danack/Imagick-demos#36]
I can´t solve after round it for all thre side: Imagick hang Apache server in XAMPP when converting PDF to PNG. 
In the attached zip, a video about the code that convert and the result in localhost, when I set a mistaken folder, there is an error message in the browser, when there´s no mistaken fodler, hang the server.

I will thnak you very much your help.

[ScreenHunter 535.zip](https://github.com/Danack/Imagick-demos/files/4574170/ScreenHunter.535.zip)

**Comment by Danack** [comment]
Hi,

I can't investigate anything from a video. 

If you can provide a code example that can be run, and the PDF file that shows the problem, I can maybe investigate.

btw it would be better to open an issue at https://github.com/imagick/imagick

**Comment by Diamond7** [comment]
Hello, thank you, I have open with code and PDF I use in https://github.com/Imagick/imagick/issues/324    , I believed I was in an imagick account, thank you for your hand, have you a very good way Danack :) !!! 

Dario Columbich (Poet & Programmer :))
