### ISSUE TITLE
Tutorial about Masking

### ISSUE THREAD

**Issue by benoitwimart** [Danack/Imagick-demos#37]
Hello,

I try to run this example on my localhost…
https://phpimagick.com/Tutorial/backgroundMasking 
But I get the same picture without checkerboard.

My best working code is :
```php
  $BackgroundColor = "rgb(255, 255, 255)";
  $img = new Imagick();
  $img->readImage('xxxxx.jpg');
  $img->setImageFormat('png'); 
  $fuzz = Imagick::getQuantum() * 0.1; // 10%
  $img->transparentPaintImage($BackgroundColor,0,$fuzz,false);
  $img->writeImage('xxxx.png');
```

Any idea ?

**Comment by Danack** [comment]
The background masking tutorial does a lot more stuff than your code does.

The code you have there will only draw 'transparent' in a small patch - like the https://phpimagick.com/Imagick/transparentPaintImage does.

....I just noticed the javascript is broken on that site, so you can't see the original image which is https://phpimagick.com/images/BlueScreen.jpg
