### ISSUE TITLE
demo for getImageHistogram

### ISSUE THREAD

**Issue by stefanellisw** [Danack/Imagick-demos#42]
Hi,
I have see the tutorial about the histogram is really well made https://phpimagick.com/Imagick/getImageHistogram

I have try to make it like this one https://bubble.ro/How_to_create_the_histogram_of_an_image_using_PHP.html in Imagick but without much success...
Could you maybe if you have some time try to do a demo for Imagick histogram like the link of bubble.ro?
With only one histogram instead of the 3 divided by colors

Thank you

**Comment by Danack** [comment]
Sorry no. I just can't justify making demos for other people right now. You should be able to modify the code to do what you want. Just change it bit by bit until it does what you want.

btw i suspect you might actually want to still have the separate colours, even if they are on top of each other on the same histogram. That could be achieved with copying the individual color channels.

```
$canvas->compositeImage($redHistogram, \Imagick::COMPOSITE_COPYRED, 0, 0);
$canvas->compositeImage($greenHistogram, \Imagick::COMPOSITE_COPYGREEN, 0, 0);
$canvas->compositeImage($blueHistogram, \Imagick::COMPOSITE_COPYBLUE, 0, 0);
```
