### ISSUE TITLE
compositeImage Error

### ISSUE THREAD

**Issue by Aljnk** [Danack/Imagick-demos#8]
Good day. I use PECL imagick on my website and have some problem with compositeImage function. I'm not sure - can I ask you about this problem? If, no - may be you can advice me where I can do this. If yes, - I have this situation:
I need add one image into another and use compositeImage for this, but result image very strange. I put my example here - http://en.allworldsms.com/test/im/test.php. This is script page with code:

<?php
$img=new Imagick();
$img->newImage(700,700,new ImagickPixel('#f0f'));
$pic=new Imagick('im.jpg');
$pic->thumbnailImage(500,500);
$img->compositeImage($pic,imagick::COMPOSITE_DEFAULT,100,100);
$img->setImageFormat("JPEG");

$img->writeImage($_SERVER["DOCUMENT_ROOT"].'/test/im/test.jpg');
$img->clear();$img->destroy();

echo '<img src="test.jpg" alt="" style="width:700px;height:700px;margin:auto;"/>';
?>

source image:
![source](https://cloud.githubusercontent.com/assets/11256478/6992848/2b0e7a88-dae9-11e4-8353-2c4d52db4404.jpg)

result image
![res](https://cloud.githubusercontent.com/assets/11256478/6992849/2b252544-dae9-11e4-81e0-d17d401124cd.jpg)

**Comment by Danack** [comment]
Hi,

The better place to report issues is https://github.com/mkoppanen/imagick/  I'll turn issues off here I think.

As for your question, the issue is that the src image is in CMYK colorspace. It looks like there is a bug in ImageMagick in handling compositing a CMYK image into an RGB image. This can be worked round in either of two ways:

i) Force the output image to be CMYK.
```
$img=new Imagick();
$img->newImage(700,700,new ImagickPixel('#f0f'));

// This sets the output image to CMYK
$img->setImageColorspace(\Imagick::COLORSPACE_CMYK);
$pic = new Imagick(realpath('worldMap.jpg'));
$pic->thumbnailImage(500,500);
$img->compositeImage($pic,imagick::COMPOSITE_DEFAULT,100,100);
$img->setImageFormat("JPEG");
$img->writeImage("worldMapOutput_cmyk.jpg");
$img->clear();
$img->destroy();


```


ii) Convert the input image to be RGB before compositing it:

```
$img=new Imagick();
$img->newImage(700,700,new ImagickPixel('#f0f'));
$pic = new Imagick(realpath('worldMap.jpg'));
$pic->thumbnailImage(500,500);

// This converts the input image to RGB
$pic->transformImageColorSpace(\Imagick::COLORSPACE_RGB);
$img->compositeImage($pic,imagick::COMPOSITE_DEFAULT,100,100);
$img->setImageFormat("JPEG");
$img->writeImage("worldMapOutput_cmyk.jpg");
$img->clear();
$img->destroy();

```

**Comment by Aljnk** [comment]
Thank you very much!!!
