### ISSUE TITLE
Requesting demo

### ISSUE THREAD

**Issue by vtjiles** [Danack/Imagick-demos#9]
Would you be able to add a demo that softens the image after calling floodFillPaintImage? The end goal would be to strip an image of it's background. I have been able to identify the main color in an image and replace it with a transparent one or another color, but the image looks pixelated when a new background is added and has remnants of the original. A tutorial for a feathering effect would be a huge help.

Before: white background
![chairs](https://cloud.githubusercontent.com/assets/4049494/7164537/d1ef3648-e36e-11e4-876f-2ea9f359bc78.jpeg)

After: gray background
![552e97ed7363055f470041aa](https://cloud.githubusercontent.com/assets/4049494/7164577/0f5f3f1e-e36f-11e4-88e6-3a1e6b8396b7.png)

**Comment by Danack** [comment]
I'll have a look - I can't make any promises.

You might be able to find something that achieves that effect on  
http://www.fmwconcepts.com/imagemagick/

**Comment by vtjiles** [comment]
Thanks, and no worries if you can't come up with something. The examples have been great in helping me understand what the different methods actually do. 

I had looked at that site and the feathering actually darkened the image a good bit so I couldn't use it. I didn't test out others though.

Shortly after putting this up here (despite searching for two days) I came across http://tech.natemurray.com/2007/12/convert-white-to-transparent.html which is perfect for what I'm looking to do. I tweaked it so the color is dynamic and it fills in all the sections instead of the outside ones so I think I can run with it. A php port would be awesome though so that files don't need to keep being written.

Appreciate the response!

**Comment by Danack** [comment]
The code below produces an image very much like:
![backgroundmasking](https://cloud.githubusercontent.com/assets/1505719/8137844/c0f6aea8-1135-11e5-940a-4dbebcee650d.png)


It's basically the same technique as the link, except it also attempts to get rid of the white outline.

```
    //Load the image
    $imagick = new \Imagick(realpath('images/chair.jpeg'));

    $backgroundColor = "rgb(255, 255, 255)";
    $fuzzFactor = 0.1;

    // Create a copy of the image, and paint all the pixels that
    // are the background color to be transparent
    $outlineImagick = clone $imagick;    
    $outlineImagick->transparentPaintImage(
        $backgroundColor, 0, $fuzzFactor * \Imagick::getQuantum(), false
    );
    
    //Convert to gray scale to make life simpler
    $mask = clone $imagick;
    $mask->transformImageColorSpace(\Imagick::COLORSPACE_GRAY);

    // DstOut does a "cookie-cutter" it leaves the shape remaining after the
    // outlineImagick image, is cut out of the mask. 
    $mask->compositeImage(
        $outlineImagick,
        \Imagick::COMPOSITE_DSTOUT,
        0, 0
    );
    
    // The mask is now black where the objects are in the image and white
    // where the background is.
    // Negate the image, to have white where the objects are and black for
    // the backgroun
    $mask->negateImage(false);
    
    $fillPixelHoles = false;
    
    if ($fillPixelHoles == true) {
        // If your image has pixel sized holes in it, you will want to fill them
        // in. This will however also make any acute corners in the image not be
        // transparent.
        
        // Fill holes - any black pixel that is surrounded by white will become
        // white
        $mask->blurimage(2, 1);
        $mask->whiteThresholdImage("rgb(10, 10, 10)");

        // Thinning - because the previous step made the outline thicker, we
        // attempt to make it thinner by an equivalent amount.
        $mask->blurimage(2, 1);
        $mask->blackThresholdImage("rgb(255, 255, 255)");
    }

    //Soften the edge of the mask to prevent jaggies on the outline.
    $mask->blurimage(2, 2);

    // We want the mask to go from full opaque to fully transparent quite quickly to 
    // avoid having too many semi-transparent pixels. sigmoidalContrastImage does this
    // for us. Values to use where determined empirically.
    $contrast = 15;
    $midpoint = 0.7 * \Imagick::getQuantum();
    $mask->sigmoidalContrastImage(true, $contrast, $midpoint);
    
    // Copy the mask into the opacity channel of the original image.
    // You are probably done here if you just want the background removed.
    $imagick->compositeimage(
        $mask,
        \Imagick::COMPOSITE_COPYOPACITY,
        0, 0
    );
    
    // To show that the background has been removed (which is difficult to see
    // against a plain white webpage) we paste the image over a checkboard
    // so that the edges can be seen.
    
    // Create the check canvas
    $canvas = new \Imagick();
    $canvas->newPseudoImage(
        $imagick->getImageWidth(),
        $imagick->getImageHeight(),
        "pattern:checkerboard"
    );

    // Copy the image with the background removed over it.
    $canvas->compositeimage($imagick, \Imagick::COMPOSITE_OVER, 0, 0);
    
    //Output the final image
    $canvas->setImageFormat('png');

    header("Content-Type: image/png");
    echo $canvas->getImageBlob();
```

**Comment by vtjiles** [comment]
Looks great, but having some issues with darker/black items. Any thoughts? 

Really appreciate you putting this together. A quick test shows it's running 15x faster than the method I am currently using!

**Comment by Danack** [comment]
Can you give an example image that doesn't work as well?

**Comment by vtjiles** [comment]
Here is one I had trouble with. I should also note I must have an older version of the library since I don't have getQuantum and instead used getQuantumRange()['quantumRangeLong']. Not sure if there were other changes/improvements across versions.

![image](https://cloud.githubusercontent.com/assets/4049494/8139148/4fe132c6-111f-11e5-9a6d-84b05f77008d.png)

**Comment by Danack** [comment]
I've updated the code above, the extra line is:
    $mask->setImageAlphaChannel(\Imagick::ALPHACHANNEL_DEACTIVATE);

As the source image has an alpha channel, which was mucking up the `$imagick->compositeimage($mask, \Imagick::COMPOSITE_COPYOPACITY, 0, 0);` as it was copying the alpha from the alpha channel rather than the colour channel as intended.


> I should also note I must have an older version of the library

Yeah.....as I'm the maintainer of the library I tend to be running the latest version. Compiling the extension is really quite easy and means you never have to wait to get stuff...

**Comment by vtjiles** [comment]
Worked great. Thanks so much for putting this together!

**Comment by Danack** [comment]
No problem, making pretty pictures is far more interesting than writing documentation...
